---
title: "Google Trends Analysis"
author: "David Liu"
date: "March 20, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message = F, warning = F, echo = F}
## Load packages we'll use
library(tidyverse)
library(reshape2)
library(foreign)
library(ggplot2)
library(gridExtra)
library(xtable)
library(pscl)
library(mvtnorm)
library(maps)

# SET WORKING DIRECTORY
# CHANGE THIS TO YOUR WORKING DIRECTORY
setwd('C:/Users/David/Google Drive/Senior Spring/SOC/firearms-replication/code')
```

## Figure 1

Load the data and store in a data frame. 
```{r}
load("../data/raw/Google Trends data for Figure 1.RData")
google_trends <- data.frame(x[3:nrow(x),]) # extrude misellaneous header data
colnames(google_trends) <- c("week", "clean", "buy")
```

Cast vaulues to be numeric from string format 
```{r}
google_trends$week <- as.numeric(google_trends$week)
google_trends$clean <- as.numeric(google_trends$clean)
google_trends$buy <- as.numeric(google_trends$buy)
```

Replicate Figure 1 from the paper:
```{r}
ggplot(data = google_trends) +
  geom_line(aes(x = week, y = clean), color = "black") +
  geom_line(aes(x = week, y = buy), color = "red") + 
  xlab("Week") +
  ylab("Index Value (100 = maximum)")
ggsave("../writing/figures/fig1_generated.PNG")
```

## Figure 2

Figure as-is
```{r}
nat_gun_sales <- read.csv("../output/figure data/fig2_sales.csv") 
nat_gun_sales$year_month <- nat_gun_sales$year + (nat_gun_sales$month - 1)/12.0
nat_gun_sales <- filter(nat_gun_sales, year <= 2015)
```

```{r}
ggplot() +
  geom_line(data = nat_gun_sales, aes(x = year_month, y = resid)) + 
  ylim(c(-1200000, 1200000)) +
  ylab("Deviation") + 
  ggtitle("Deviations from Expected Monthly Firearm Sales: Pre-revision") 
ggsave("../writing/figures/fig2_pre_revision.PNG")
```

Remove 2016 data
```{r}
nat_gun_sales <- read.csv("../output/figure data/fig2_sales_revised.csv") 
nat_gun_sales$year_month <- nat_gun_sales$year + (nat_gun_sales$month - 1)/12.0
nat_gun_sales <- filter(nat_gun_sales, year <= 2015)
```

```{r}
ggplot() +
  geom_line(data = nat_gun_sales, aes(x = year_month, y = resid)) + 
  ylim(c(-1200000, 1200000)) +
  ylab("Deviation") + 
  ggtitle("Deviations from Expected Monthly Firearm Sales") 
ggsave("../writing/figures/fig2_sales.PNG")
```

Load the death data
```{r}
nat_death <- read.csv("../output/figure data/fig2_deaths.csv")
```

```{r}
ggplot(data = nat_death) +
  geom_bar(aes(x = year, weight = resid), width = 0.417) + 
  ylim(c(-0.024, 0.024)) +
  ylab("Deviation") + 
  ggtitle("Deviations from Expected Accidental Firearm Death Rates for Children") 
ggsave("../writing/figures/fig2_deaths.PNG")
# set bar width to 5 months 
```

## Figure 3

Setup the dataframe for state level firearm sale increases:
```{r}
states_gun_increase <- read.csv("../output/figure data/fig3.csv")
states_map <- map_data("state")
ggplot(states_gun_increase, aes(map_id = state)) +
    geom_map(aes(fill = -total_increase), map = states_map)+
    expand_limits(x = states_map$long, y = states_map$lat)
ggsave("../writing/figures/fig3_generated.png")
```